# -----------------------------------------------------------------------------
# ETAPA 1: Construcción (Builder)
# Usamos una imagen que ya tenga Maven y Java 21 para compilar
# -----------------------------------------------------------------------------
FROM maven:3.9.6-eclipse-temurin-21 AS builder

WORKDIR /usr/src/app

# 1. Copiamos los archivos de configuración de Maven primero
# Esto permite a Docker cachear las dependencias si el pom.xml no cambia
COPY pom.xml .

RUN echo "---- CONTENIDO DEL DIRECTORIO ACTUAL EN DOCKER ----" && ls -la

# 2. Descargamos las dependencias (Go Offline)
# Este paso acelera builds futuros al no descargar internet si no cambias dependencias
RUN mvn dependency:go-offline

# 3. Copiamos el código fuente
COPY src src


# 4. Empaquetamos la aplicación
# -DskipTests ahorra tiempo en la creación de la imagen
RUN mvn package -DskipTests

# -----------------------------------------------------------------------------
# ETAPA 2: Ejecución (Runtime)
# Esta es tu imagen original, pero ahora copia desde la etapa "builder"
# -----------------------------------------------------------------------------
FROM registry.access.redhat.com/ubi8/openjdk-21:1.20

ENV LANGUAGE='en_US:en'

# OJO: Aquí la magia. Usamos "--from=builder" para traer los archivos compilados
# Nota: La ruta origen es /usr/src/app/target/... porque así lo definimos en el builder
COPY --from=builder --chown=185 /usr/src/app/target/quarkus-app/lib/ /deployments/lib/
COPY --from=builder --chown=185 /usr/src/app/target/quarkus-app/*.jar /deployments/
COPY --from=builder --chown=185 /usr/src/app/target/quarkus-app/app/ /deployments/app/
COPY --from=builder --chown=185 /usr/src/app/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185

ENTRYPOINT ["java","-jar", "/deployments/quarkus-run.jar"]